#!/usr/bin/env bash
# Install nginx on your web-01 server.
# redirection permanently to another page.

sudo apt-get update
sudo apt-get -y install nginx
sudo echo "Holberton School" > /var/www/html/index.html
sudo sed -i '/root \/var\/www\/html;/a location = /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default
sudo service nginx start
