#!/usr/bin/env bash
# Install nginx on your web-01 server.
# redirection permanently to another page.

apt-get update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
sudo ufw allow 'Nginx HTTP'
sed -i '/root \/var\/www\/html;/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=uDrdZM1iGrc permanent; }' /etc/nginx/sites-available/default
service nginx start
