#!/usr/bin/env bash
# configure new Load balanncer
# Install and config haproxy on load balancer 
apt-get update
apt-get -y install haproxy

printf "\nbackend web-backend\n\
\tbalance roundrobin\n\
\tserver web1 35.243.241.181:80\n\
\tserver web2 3.87.74.240:80\n\n
frontend haproxynode\n\
\tbind *:80\n\
\tmode http\n\
\tdefault_backend web-backend\n" >> /etc/haproxy/haproxy.cfg

service haproxy restart
