#!/usr/bin/env bash
# this script displays a string indefinitely,
# adding sleep bewteen each iteration and sigterm

trap "echo I am invincible!!!" SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done
