#!/usr/bin/env bash
# This script displays numbers from 1 to 100.
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5

counter=1
while [ "$counter" -lt 101 ]
do
    if [ $((counter%15)) = 0 ]
    then
        echo "FizzBuzz"
    elif [ $((counter%3)) = 0 ]
    then
        echo "Fizz"
    elif [ $((counter%5)) = 0 ]
    then
        echo "Buzz"
    else
            echo "$counter"
    fi
((counter++))
done
