#!/usr/bin/env bash
# this scrip displays username, user id and home directory
# of the  /etc/passwd.

FILENAME="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d':' -f1,3,6
done < "$FILENAME"
