#!/usr/bin/env bash
# this scrip displaying information about the holbertonschool file.
FILE="holbertonschool"

if [ -e "$FILE" ]
then
    echo "$FILE file exists"
else
    echo "$FILE file does not exist"
fi

if [ -s "$FILE" ]
then
    echo "$FILE file is not empty"
else
    echo "$FILE file is empty"
fi

if [ -f "$FILE" ]
then
    echo "$FILE is a regular file"
fi
