#!/usr/bin/env bash
# Changes firewall (ufw) configurations 
sudo ufw default deny incoming 
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable #habilitar servicio 
sudo ufw status # check the current UFW releset
